In [20]:
import math 
import time
import timeit
import numpy as np
from itertools import permutations
from scipy.sparse import csr_matrix
from scipy.io import mmread
import scipy as sp

#carrega matriz, função provisoria
def load_matriz():
    matriz = open("mycielskian3.mtx", "r")
    return matriz

#retorna a lista de vertices adj
def edges(vertex, matadj):
    ret = []
    if(vertex not in range(len(matadj))):
        raise Exception   
    for j in range (len(matadj[vertex])):
        if(vertex != j and matadj[vertex][j]>0):
            ret.append(j)            
    return ret

#recebe primeiramente meu limite maximo como infinito
#matriz dentro de uma matriz dentro de outro array, detalhe do 0
#tag vai atribuir     
#retorna todas arestas destes vertices
def bandwidth_v(vertex, matadj, tags):
    maxim =-math.inf        
    vertices = edges(vertex, matadj)   
    for i in range(len(vertices)):
        maxim = max(maxim, abs(tags[vertices[i]]-tags[vertex]))
    return maxim

#calcular todos os vertices, The bandwidth of the graph G under f is :    
def bandwidth_matriz(matadj,tags):
    maxim =-math.inf
    for i in range(len(matadj)):
        maxim = max(maxim, bandwidth_v(i, matadj, tags)) 
    return maxim

#calcula meu minimo bandwidht
def bandwidth_min(matadj):
    minlist = []
    minim = math.inf
    size=len(matadj)
    for it in permutations(range(size), size):        
        listit = list(it)
        band = bandwidth_matriz(matadj, listit)        
        if minim > band:           
            minim = band
            minlist = listit      
    return minim, minlist

def dic_list(listd):
    dic={}
    for i in range(len(listd)):
        dic[listd[i]]=i
    return dic
  
def bandwidth_min_graph(matadj, list_minbw):    
    newmatadj = np.zeros((len(matadj),len(matadj)))
    diclist = dic_list(list_minbw)
  
    for i in range(len(matadj)):
        for j in range(len(matadj)):
            if matadj[i][j]==1:
                newmatadj[diclist[i]][diclist[j]] = 1
                newmatadj[diclist[j]][diclist[i]] = 1            
    return newmatadj 

def to_adj_matriz(m_a): # Recebe uma matriz de adjacencia csr
    n_vx = m_a.shape[0]
    n_vy = m_a.shape[1]

    adj_m = np.zeros((n_vx,n_vy))
    for i in range(n_vx):
        adj_m[i][i]=1
        for j in range(n_vy):
            if (m_a[i,j] != 0):
                adj_m[i][j]=1             
    return adj_m

if __name__ == '__main__':     
    t_init = time.time()
    temp_matriz=sp.io.mmread(load_matriz()).tocsr()
    matadj = to_adj_matriz(temp_matriz)  
    b_minim, minlist = bandwidth_min(matadj)
    
   # print('Largura de banda da matriz inicial: ',b_maxim,'\n')
    print('Largura de banda da matriz final:',b_minim)   
    print('Tempo de execução: ', time.time() - t_init,'s\n')
    #print('Arranjo: \n',minlist)
    #print('Matriz Permutada: \n',bandwidth_min_graph(matadj,minlist))    
    

Largura de banda da matriz final: 2
Tempo de execução:  0.01599717140197754 s

Matriz Permutada: 
 [[1. 1. 1. 0. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1.]]
